/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "enter"
      | "entropyOracle"
      | "getEncryptedEntropy"
      | "getEntropyOracle"
      | "getStatus"
      | "hasParticipated"
      | "isEntropyStored"
      | "lotteryComplete"
      | "lotteryRound"
      | "participants"
      | "requestEntropy"
      | "resetLottery"
      | "selectWinnerWithEntropy"
      | "winner"
      | "winningRequestId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyStored"
      | "LotteryReset"
      | "LotteryStarted"
      | "ParticipantAdded"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "enter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEntropy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasParticipated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEntropyStored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryComplete",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectWinnerWithEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "winningRequestId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEntropyStored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectWinnerWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningRequestId",
    data: BytesLike
  ): Result;
}

export namespace EntropyStoredEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LotteryResetEvent {
  export type InputTuple = [newRound: BigNumberish];
  export type OutputTuple = [newRound: bigint];
  export interface OutputObject {
    newRound: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LotteryStartedEvent {
  export type InputTuple = [round: BigNumberish];
  export type OutputTuple = [round: bigint];
  export interface OutputObject {
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantAddedEvent {
  export type InputTuple = [participant: AddressLike, round: BigNumberish];
  export type OutputTuple = [participant: string, round: bigint];
  export interface OutputObject {
    participant: string;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    winner: AddressLike,
    requestId: BigNumberish,
    round: BigNumberish
  ];
  export type OutputTuple = [winner: string, requestId: bigint, round: bigint];
  export interface OutputObject {
    winner: string;
    requestId: bigint;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleLottery extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleLottery;
  waitForDeployment(): Promise<this>;

  interface: SimpleLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  enter: TypedContractMethod<[], [void], "nonpayable">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getEncryptedEntropy: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getStatus: TypedContractMethod<
    [],
    [
      [bigint, boolean, string, bigint] & {
        participantCount: bigint;
        complete: boolean;
        currentWinner: string;
        currentRound: bigint;
      }
    ],
    "view"
  >;

  hasParticipated: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isEntropyStored: TypedContractMethod<[], [boolean], "view">;

  lotteryComplete: TypedContractMethod<[], [boolean], "view">;

  lotteryRound: TypedContractMethod<[], [bigint], "view">;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  resetLottery: TypedContractMethod<[], [void], "nonpayable">;

  selectWinnerWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  winner: TypedContractMethod<[], [string], "view">;

  winningRequestId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedEntropy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, boolean, string, bigint] & {
        participantCount: bigint;
        complete: boolean;
        currentWinner: string;
        currentRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasParticipated"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEntropyStored"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lotteryComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lotteryRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "resetLottery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectWinnerWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winningRequestId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntropyStored"
  ): TypedContractEvent<
    EntropyStoredEvent.InputTuple,
    EntropyStoredEvent.OutputTuple,
    EntropyStoredEvent.OutputObject
  >;
  getEvent(
    key: "LotteryReset"
  ): TypedContractEvent<
    LotteryResetEvent.InputTuple,
    LotteryResetEvent.OutputTuple,
    LotteryResetEvent.OutputObject
  >;
  getEvent(
    key: "LotteryStarted"
  ): TypedContractEvent<
    LotteryStartedEvent.InputTuple,
    LotteryStartedEvent.OutputTuple,
    LotteryStartedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantAdded"
  ): TypedContractEvent<
    ParticipantAddedEvent.InputTuple,
    ParticipantAddedEvent.OutputTuple,
    ParticipantAddedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "EntropyStored(uint256)": TypedContractEvent<
      EntropyStoredEvent.InputTuple,
      EntropyStoredEvent.OutputTuple,
      EntropyStoredEvent.OutputObject
    >;
    EntropyStored: TypedContractEvent<
      EntropyStoredEvent.InputTuple,
      EntropyStoredEvent.OutputTuple,
      EntropyStoredEvent.OutputObject
    >;

    "LotteryReset(uint256)": TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;
    LotteryReset: TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;

    "LotteryStarted(uint256)": TypedContractEvent<
      LotteryStartedEvent.InputTuple,
      LotteryStartedEvent.OutputTuple,
      LotteryStartedEvent.OutputObject
    >;
    LotteryStarted: TypedContractEvent<
      LotteryStartedEvent.InputTuple,
      LotteryStartedEvent.OutputTuple,
      LotteryStartedEvent.OutputObject
    >;

    "ParticipantAdded(address,uint256)": TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;
    ParticipantAdded: TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;

    "WinnerSelected(address,uint256,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
