/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "enter"
      | "entropyOracle"
      | "getStatus"
      | "hasParticipated"
      | "lotteryComplete"
      | "lotteryRound"
      | "participants"
      | "resetLottery"
      | "selectWinner"
      | "winner"
      | "winningRequestId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LotteryReset"
      | "LotteryStarted"
      | "ParticipantAdded"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(functionFragment: "enter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasParticipated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryComplete",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetLottery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectWinner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "winningRequestId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningRequestId",
    data: BytesLike
  ): Result;
}

export namespace LotteryResetEvent {
  export type InputTuple = [newRound: BigNumberish];
  export type OutputTuple = [newRound: bigint];
  export interface OutputObject {
    newRound: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LotteryStartedEvent {
  export type InputTuple = [round: BigNumberish];
  export type OutputTuple = [round: bigint];
  export interface OutputObject {
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantAddedEvent {
  export type InputTuple = [participant: AddressLike, round: BigNumberish];
  export type OutputTuple = [participant: string, round: bigint];
  export interface OutputObject {
    participant: string;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    winner: AddressLike,
    requestId: BigNumberish,
    round: BigNumberish
  ];
  export type OutputTuple = [winner: string, requestId: bigint, round: bigint];
  export interface OutputObject {
    winner: string;
    requestId: bigint;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleLottery extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleLottery;
  waitForDeployment(): Promise<this>;

  interface: SimpleLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  enter: TypedContractMethod<[], [void], "nonpayable">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getStatus: TypedContractMethod<
    [],
    [
      [bigint, boolean, string, bigint] & {
        participantCount: bigint;
        complete: boolean;
        currentWinner: string;
        currentRound: bigint;
      }
    ],
    "view"
  >;

  hasParticipated: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  lotteryComplete: TypedContractMethod<[], [boolean], "view">;

  lotteryRound: TypedContractMethod<[], [bigint], "view">;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  resetLottery: TypedContractMethod<[], [void], "nonpayable">;

  selectWinner: TypedContractMethod<[], [void], "payable">;

  winner: TypedContractMethod<[], [string], "view">;

  winningRequestId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, boolean, string, bigint] & {
        participantCount: bigint;
        complete: boolean;
        currentWinner: string;
        currentRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasParticipated"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lotteryComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lotteryRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "resetLottery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectWinner"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winningRequestId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LotteryReset"
  ): TypedContractEvent<
    LotteryResetEvent.InputTuple,
    LotteryResetEvent.OutputTuple,
    LotteryResetEvent.OutputObject
  >;
  getEvent(
    key: "LotteryStarted"
  ): TypedContractEvent<
    LotteryStartedEvent.InputTuple,
    LotteryStartedEvent.OutputTuple,
    LotteryStartedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantAdded"
  ): TypedContractEvent<
    ParticipantAddedEvent.InputTuple,
    ParticipantAddedEvent.OutputTuple,
    ParticipantAddedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "LotteryReset(uint256)": TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;
    LotteryReset: TypedContractEvent<
      LotteryResetEvent.InputTuple,
      LotteryResetEvent.OutputTuple,
      LotteryResetEvent.OutputObject
    >;

    "LotteryStarted(uint256)": TypedContractEvent<
      LotteryStartedEvent.InputTuple,
      LotteryStartedEvent.OutputTuple,
      LotteryStartedEvent.OutputObject
    >;
    LotteryStarted: TypedContractEvent<
      LotteryStartedEvent.InputTuple,
      LotteryStartedEvent.OutputTuple,
      LotteryStartedEvent.OutputObject
    >;

    "ParticipantAdded(address,uint256)": TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;
    ParticipantAdded: TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;

    "WinnerSelected(address,uint256,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
